### ISSUE TITLE
Significant Lag and Timeouts

### ISSUE THREAD

**Issue by alexgalbraith** [ShrimpCryptid/Secret-Hitler-Online#40]
Was trying this evening in advance of a group game tomorrow - site is lagging when creating a lobby, long period of nothing, then suddenly jumps to life. Then added a player, player joined and the room then timed out and booted out the first player. 3rd player added and connected very quickly. Seems very variable. Not stable enough to use at the moment. Thanks!

**Comment by ShrimpCryptid** [comment]
Thanks for opening an issue!

So, some slowdown is expected when first starting up the game. This is because the hosting service I'm using puts the server to sleep when it's not in active use, and wakes it up as the backend is queried. It should be loading as soon as the website gets opened though, and you shouldn't experience any issues after the first 5-10 seconds since the backend will be fully awake.

I'm not sure what was causing the timeouts for the player joining, however. Were you able to rejoin as that player after being disconnected?

Also, how long was the time period you were testing this over?

**Comment by alexgalbraith** [comment]
Testing was over 10 mins or so. Checked again today and performance is back to normal - ran a 5 player test and it worked perfectly. My guess is an infra / server performance issue, not a code issue last night.

**Comment by ShrimpCryptid** [comment]
Okay, I'll go ahead and mark this issue as closed unless you start to encounter issues again.

Thank you for reaching out, and hope you have a fun game night!
